### ISSUE TITLE
Wrong paragraph, wrong place for paragraph or words not replaced?

### ISSUE THREAD

**Issue by UrsulaE** [nfdi4plants/ARC-specification#114]
https://github.com/nfdi4plants/ARC-specification/blob/main/ARC%20specification.md#study-and-resources

Last paragraph reads 
"Further explications about data entities defined in the **assay** MAY be stored in ISA-XLSX format in a isa.datamap.xlsx file, which SHOULD exist for each **assay**. Further details on isa.datamap.xlsx are specified in the isa-xlsx specification."
(**bold** by me)

The same paragraph is included in the instructions under "Assay Data and Metadata" (3rd paragraph).

Would it be right to assume that **assay** should read **study** here under the heading studies?

**Comment by kMutagene** [comment]
cc @HLWeil

**Comment by HLWeil** [comment]
Thanks for your input, @UrsulaE. Yup this is definitely a copy error.
