### ISSUE TITLE
Confusing ontology examples in Isa specification

### ISSUE THREAD

**Issue by UrsulaE** [nfdi4plants/ARC-specification#115]
The instructions of how to refer to ontology terms (https://github.com/nfdi4plants/ARC-specification/blob/main/ISA-XLSX.md#ontology-annotations) seem to disagree between the description text, use "\<IDSPACE>:\<LOCALID>", and the examples in which in the first example (NCBITaxon) the respective obo link http://... is given, in a later example (Liver) the source ontology (Mesh) omitted with the term id (D008099). 

a. I realize that there may not be any real disagreement, only different notations. 
b. The URIs in the examples include links. Tools like swate-alpha only allow the insertion of simple text, not links. 

Looks like these examples come directly from https://isa-specs.readthedocs.io/en/latest/isatab.html#ontology-annotations, which may explain the differences. Given that this is a reference text for users from different realms, I feel it would be better to resolve the disagreement (even if it was not real) by giving more explanations or by adjusting the examples to the text.

**Comment by HLWeil** [comment]
Hey @UrsulaE,

thanks for your feedback. 

## Explanations to your points

> a. I realize that there may not be any real disagreement, only different notations.

Yes, for referencing a given ontology Ontology terms, we use two distinct notations:

1. **URI notation**: Full URL linking to the Annotation term
  e.g. `http://purl.obolibrary.org/obo/OBI_0003114`

2. **Short accession**:  \<IDSPACE\>:\<LOCALID\>
  e.g. `OBI:0003114`

As the URL for the value, both annotation can be used. In the header, only the short annotation is allowed. The text only refers to the headers, which is probably what caused the confusion. 

> b. The URIs in the examples include links. Tools like swate-alpha only allow the insertion of simple text, not links.

The URIs and short-annotations are basically interchangeable in the datamodel and parsing. Swate-Alpha only showing the Short accession is just a matter of display.

E.g. this table in swate-alpha 

![image](https://github.com/user-attachments/assets/6cf9e985-c9e8-4bc0-a233-231653afa06b)

will look like this when downloaded:

![image](https://github.com/user-attachments/assets/8899eb1d-c7e2-4190-967c-fcec3612f65f)

## Possible Solution

Maybe I could add some explanations about the range of the values (as opposed to the columns) and make a distinction there? Let me know if this would help clear up the confusing elements in the specs.

**Comment by UrsulaE** [comment]
Thanks, Lucas, for your replies. Ursula

**Comment by HLWeil** [comment]
@UrsulaE, I closed this issue as the PR containing the changes was merged. 

I hope the incorporated explanations answer your confusion. If not, feel free to reopen!
