### ISSUE TITLE
Relative paths

### ISSUE THREAD

**Issue by kappe-c** [nfdi4plants/ARC-specification#56]
In a few places the spec mentions _relative paths_, e.g. as used in a cwl file. It is a bit ambiguous whether this means relative to the root directory of the ARC (as opposed to an absolute path on the user's machine) or relative to the (cwl, xlsx, etc) file where the path appears. So e.g. in workflows/foo/foo.cwl a path could be given in these two ways:
option 1: ./runs/run1/foo.csv (optional leading ./)
option 2: ../../runs/run1/foo.csv
If there is agreement on which option is intended, could this maybe be clarified in the spec? Maybe with an example as above.

**Comment by kappe-c** [comment]
Today I learned that paths in cwl (and corresponding yml) files must be relative to the present working directory of cwl-runner (when somebody uses this tool in order to reproduce results). So,

1. this specification could have different rules/guidelines for the cwl/yml files and the isa.*.xlsx files.
2. the question raised in my previos post, which notion of relative is meant, should rather be, from which directory is a user expected to run cwl-runner.

If the goal is that any ARC can be reproduced with sth like `cwl-runner arc.cwl` but also e.g. `cwl-runner workflows/workflow1/workflow.cwl`, then above option 1 should be the standard. However, I think it is quite common to `cd` into the directory that contains the cwl file; and some tools may change the present working directory as they execute …

**Comment by HLWeil** [comment]
After some consideration, I think `option 1` would be better. If all paths are specified relative from the ARC root, there is no ambiguity. 
Also like this there is no need to have different rules for different tools or different parts of the ARC. It might be one rule to rule them all.

**Comment by omaus** [comment]
Current validation tests work on option 1 btw. 😅
