### ISSUE TITLE
Is top-level arc.cwl optional or a must?

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/ARC-specification#58]
`ARC specification.md` says

> Top-level metadata and workflow description tie together the elements of an ARC in the contexts of investigation and associated studies (in the ISA definition), captured in the file isa.investigation.xlsx in [ISA-XLSX format](https://github.com/nfdi4plants/ARC-specification/blob/main/ARC%20specification.md#isa-xlsx-format), which MUST be present. Furthermore, top-level reproducibility information MUST be provided in the CWL arc.cwl, which also MUST exist.

and further

> Top-Level Run Description
> 
> The file arc.cwl MUST exist at the root directory of each ARC. It describes which runs are executed (and specifically, their order) to (re)produce the computational outputs contained within the ARC.

but in the Example below it's

![image](https://user-images.githubusercontent.com/47781170/190630215-4fed8f3c-c13b-43b3-bb54-0f6647c6e6a4.png)

So what is it now? Optional or required?

**Comment by eik-dahms** [comment]
Same Question here

**Comment by HLWeil** [comment]
Maybe we could change `MUST` to `SHOULD`.

**Comment by kMutagene** [comment]
@HLWeil you mean we `MUST` change `MUST` to `SHOULD` ? 😆
