### ISSUE TITLE
Metadata section sheets differ in naming

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/ARC-specification#65]
`isa.investigation.xlsx`, `isa.study.xlsx`, `isa.assay.xlsx` differ in the name of the worksheet containing the metadata section. For Study and Assay it is "Study" and "Assay", respectively. For Investigation, it is "isa_investigation" which differs.

***Solution***
Either rename Investigation metadata section worksheet into "Investigation" -OR- Study/Assay metadata section worksheet into "isa_study"/"isa_assay".

**Comment by HLWeil** [comment]
included in #72
