### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARC-specification#70]
The ARC specification has currently two licenses listed in the opening section 

> This specification is Copyright 2022 by [DataPLANT](https://nfdi4plants.de).
> 
> Licensed under the Creative Commons License CC BY, Version 4.0; you may not use this file except in compliance with the License. You may obtain a copy of the License at https://creativecommons.org/about/cclicenses/. This license allows re-users to distribute, remix, adapt, and build upon the material in any medium or format, so long as attribution is given to the creator. The license allows for commercial use. Credit must be given to the creator.

**Comment by HLWeil** [comment]
@muehlhaus @CMR248 @chgarth 

Any ideas about the legal situation here? I guess this should be fixed for the next release.

**Comment by Brilator** [comment]
Might actually not be an issue. At least that's also what you see for journal publications. 

Check "information" on the right 
https://onlinelibrary.wiley.com/doi/full/10.1111/tpj.16474#pane-pcw-details

**Comment by Brilator** [comment]
https://creativecommons.org/get-cc-savvy/copyright-creativecommons-are-friends/

**Comment by HLWeil** [comment]
Oh okay I see, so the Copyright statement is just used to tell people whom to ask for permissions beyond the creative commons license. Will close this then, thanks for the link 👍
