### ISSUE TITLE
Add `Image Directory` Node type for Input/Output

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/ARC-specification#82]
I have seen there is an `Image File` Material Node

https://github.com/nfdi4plants/ARC-specification/blob/427935a6fe27ba611891e79027da4c86b82e1704/ISA-XLSX.md?plain=1#L626

 maybe we can add `Image Directory` (or something along those lines) to allow for a single node that contains image series, e.g. for omero @HLWeil ?

**Comment by HLWeil** [comment]
Following an offline discussion about reducing (unneeded) specificity of the IO entity types:

How about we switch from
```
Raw Data File
Derived Data File
Image File
```
to
```
Data File
Data Directory
```
The reasoning would be the following:
1. Currently, there is no way to annotate directories, which we will definitely need.
2. Distinction between `Raw` and `Derived` is kind of arbitrary (and can possibly be derived from the process graph)
3. Why is there `Image File`, but not `Binary File` or `Text File` or `Video File` or whatever. Questions regarding this level of specifity could be endless.

**Comment by HLWeil** [comment]
@Freymaurer @Brilator @muehlhaus

**Comment by kMutagene** [comment]
this is the way

**Comment by Freymaurer** [comment]
lgtm

**Comment by kMutagene** [comment]
Maybe even go a step further and default to `Material Name` in the data model when there is only `Output` without brackets?

**Comment by Brilator** [comment]
> directories, which we will definitely need

why? 

Strongly agree with the other two points.

**Comment by kMutagene** [comment]
> > directories, which we will definitely need

> why?

While working through the imaging use cases, the need for treating a directory that contains a set of files as a single entity (meaning one output node) became obvious.
